const syno = ["hi", "hello", "bye"];

const showSynms = (arr) => {
  const itemsSyno = arr.map((item) => `hhh`);
  console.log(itemsSyno.join(" "));
};
showSynms(syno);



{/* <span class="btn">${wordDetails.synonyms[0]?wordDetails.synonyms[0]:"😖" }</span>
          <span class="btn">${wordDetails.synonyms[1]?wordDetails.synonyms[1]:"😖"}</span>
          <span class="btn">${wordDetails.synonyms[2]?wordDetails.synonyms[2]:"😖"}</span> */}